CREATE TABLE "HOBBY" (
	"HOBBY_CODE"	NUMBER		NOT NULL,
	"HOBBY_NAME"	NVARCHAR2(20)		NOT NULL,
	"HOBBY_ICON"	NVARCHAR2(200)		NULL,
	"PARENT_CODE"	NUMBER		NULL,
	"HOBBY_LEVEL"	NUMBER		NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL
);


ALTER TABLE HOBBY MODIFY HOBBY_CODE NUMBER;

COMMENT ON COLUMN "HOBBY"."HOBBY_CODE" IS '취미 코드 (PK)';

COMMENT ON COLUMN "HOBBY"."HOBBY_NAME" IS '취미명';

COMMENT ON COLUMN "HOBBY"."HOBBY_ICON" IS '취미 아이콘';

COMMENT ON COLUMN "HOBBY"."PARENT_CODE" IS '취미 부모 코드 (FK)';

COMMENT ON COLUMN "HOBBY"."HOBBY_LEVEL" IS '취미 레벨';

COMMENT ON COLUMN "HOBBY"."BOARD_CODE" IS '게시판 코드 번호 (FK)';

INSERT INTO HOBBY VALUES
(1, '운동-레저', 'fa-solid fa-baseball', NULL, 1, 2);

INSERT INTO HOBBY VALUES
(2, '문화-예술', 'fa-solid fa-palette', NULL, 1, 2);

INSERT INTO HOBBY VALUES
(3, '자기 계발', 'fa-solid fa-lightbulb', NULL, 1, 2);

INSERT INTO HOBBY VALUES
(4, '사회 교류', 'fa-solid fa-users', NULL, 1, 2);

INSERT INTO HOBBY VALUES
(5, '수집-소비', 'fa-solid fa-box-archive', NULL, 1, 2);

INSERT INTO HOBBY VALUES (101, '러닝', 'fa-solid fa-person-running', 1, 2, 2);
INSERT INTO HOBBY VALUES (102, '헬스', 'fa-solid fa-dumbbell', 1, 2, 2);
INSERT INTO HOBBY VALUES (103, '등산', 'fa-solid fa-person-hiking', 1, 2, 2);
INSERT INTO HOBBY VALUES (104, '사이클', 'fa-solid fa-bicycle', 1, 2, 2);
INSERT INTO HOBBY VALUES (105, '볼링', 'fa-solid fa-bowling-ball', 1, 2, 2);
INSERT INTO HOBBY VALUES (106, '탁구', 'fa-solid fa-table-tennis-paddle-ball', 1, 2, 2);
INSERT INTO HOBBY VALUES (107, '수영', 'fa-solid fa-person-swimming', 1, 2, 2);
INSERT INTO HOBBY VALUES (108, '축구', 'fa-solid fa-futbol', 1, 2, 2);
INSERT INTO HOBBY VALUES (109, '야구', 'fa-solid fa-baseball-bat-ball', 1, 2, 2);
INSERT INTO HOBBY VALUES (110, '골프', 'fa-solid fa-golf-ball-tee', 1, 2, 2);

INSERT INTO HOBBY VALUES (201, '드로잉', 'fa-solid fa-palette', 2, 2, 2);
INSERT INTO HOBBY VALUES (202, '캘리그라피', 'fa-solid fa-paintbrush', 2, 2, 2);
INSERT INTO HOBBY VALUES (203, '사진 촬영', 'fa-solid fa-camera', 2, 2, 2);
INSERT INTO HOBBY VALUES (204, '영상 편집', 'fa-solid fa-video', 2, 2, 2);
INSERT INTO HOBBY VALUES (205, '악기 연주', 'fa-solid fa-guitar', 2, 2, 2);
INSERT INTO HOBBY VALUES (206, '도예/공예', 'fa-solid fa-compass-drafting', 2, 2, 2);
INSERT INTO HOBBY VALUES (207, '전시회·공연 관람', 'fa-solid fa-landmark', 2, 2, 2);


INSERT INTO HOBBY VALUES (301, '독서', 'fa-solid fa-book', 3, 2, 2);
INSERT INTO HOBBY VALUES (302, '글쓰기', 'fa-solid fa-pen-fancy', 3, 2, 2);
INSERT INTO HOBBY VALUES (303, '코딩', 'fa-solid fa-code', 3, 2, 2);
INSERT INTO HOBBY VALUES (304, '외국어 공부', 'fa-solid fa-language', 3, 2, 2);
INSERT INTO HOBBY VALUES (305, '요리', 'fa-solid fa-kitchen-set', 3, 2, 2);
INSERT INTO HOBBY VALUES (306, '재테크/투자', 'fa-solid fa-sack-dollar', 3, 2, 2);

INSERT INTO HOBBY VALUES (401, '봉사활동', 'fa-solid fa-handshake-angle', 4, 2, 2);
INSERT INTO HOBBY VALUES (402, '북클럽', 'fa-solid fa-book-open-reader', 4, 2, 2);
INSERT INTO HOBBY VALUES (403, '보드게임 모임', 'fa-solid fa-chess-board', 4, 2, 2);
INSERT INTO HOBBY VALUES (404, '취미 클래스', 'fa-solid fa-chalkboard-user', 4, 2, 2);
INSERT INTO HOBBY VALUES (405, '스포츠 동호회', NULL, 4, 2, 2);
INSERT INTO HOBBY VALUES (406, '스터디 모임', 'fa-solid fa-graduation-cap', 4, 2, 2);
INSERT INTO HOBBY VALUES (407, '그룹 운동', 'fa-solid fa-people-pulling', 4, 2, 2);

INSERT INTO HOBBY VALUES (501, '피규어/굿즈 수집', NULL, 5, 2, 2);
INSERT INTO HOBBY VALUES (502, '음반/LP 수집', 'fa-solid fa-record-vinyl', 5, 2, 2);
INSERT INTO HOBBY VALUES (503, '향수 수집', NULL, 5, 2, 2);
INSERT INTO HOBBY VALUES (504, '패션 아이템 수집', 'fa-solid fa-shirt', 5, 2, 2);
INSERT INTO HOBBY VALUES (505, '문구류 수집', 'fa-solid fa-pen', 5, 2, 2);
INSERT INTO HOBBY VALUES (506, '한정판/콜라보 수집', NULL, 5, 2, 2);

COMMIT;

SELECT * FROM HOBBY;

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	NVARCHAR2(30)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NULL,
	"MEMBER_ADDRESS"	NVARCHAR2(300)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"AUTHOR_LEVEL"	NUMBER	DEFAULT 1	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."AUTHOR_LEVEL" IS '회원 권한 등급';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 탈퇴 여부';

ALTER TABLE "MEMBER" ADD PROFILE_IMG VARCHAR2(300);
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';

SELECT * FROM MEMBER;

CREATE TABLE "PENALTY" (
	"PENALTY_NO"	NUMBER		NOT NULL,
	"PENALTY_TYPE"	VARCHAR2(20)		NOT NULL,
	"PENALTY_START_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PENALTY_END_DATE"	DATE		NULL,
	"PENALTY_REASON"	NVARCHAR2(100)		NOT NULL,
	"PENALTY_STATUS" VARCHAR2(40) DEFAULT 'ACTIVE' NOT NULL, 
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PENALTY"."PENALTY_NO" IS '제재 번호 (PK)';

COMMENT ON COLUMN "PENALTY"."PENALTY_TYPE" IS '제재 유형';

COMMENT ON COLUMN "PENALTY"."PENALTY_START_DATE" IS '제재 시작일';

COMMENT ON COLUMN "PENALTY"."PENALTY_END_DATE" IS '제재 종료일';

COMMENT ON COLUMN "PENALTY"."PENALTY_REASON" IS '제재 사유';

COMMENT ON COLUMN "PENALTY"."PENALTY_STATUS" IS '제재 사유';

COMMENT ON COLUMN "PENALTY"."MEMBER_NO" IS '회원 번호(PK)';

CREATE SEQUENCE SEQ_PENALTY_NO NOCACHE;

CREATE TABLE "MEMBER_HOBBY" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"HOBBY_CODE"	NUMBER		NOT NULL
);


COMMENT ON COLUMN "MEMBER_HOBBY"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "MEMBER_HOBBY"."HOBBY_CODE" IS '취미 코드 (PK)';

CREATE TABLE "QUESTION" (
	"QUESTION_NO"	NUMBER		NOT NULL,
	"QUESTION_CONTENT"	NVARCHAR2(200)		NOT NULL
);

INSERT INTO QUESTION VALUES (1, '결과보다 과정이 예쁘거나 재밌으면 만족한다.');
INSERT INTO QUESTION VALUES (2, '쓸모없지만 재밌는 것보다는, 쓸모 있는 것이 좋다.');
INSERT INTO QUESTION VALUES (3, '활동 자체보다 그 안에서 생기는 관계가 중요하다.');
INSERT INTO QUESTION VALUES (4, '관심 있는 분야는 알아보다가 장비나 굿즈까지 보게 된다.');
INSERT INTO QUESTION VALUES (5, '피곤해도 움직이고 나면 오히려 개운해진다.');
INSERT INTO QUESTION VALUES (6, '정답 없는 문제를 만났을 때 오히려 흥미가 생긴다.');
INSERT INTO QUESTION VALUES (7, '좋아하는 것과 좋아하지 않는 것이 비교적 분명한 편이다.');
INSERT INTO QUESTION VALUES (8, '약속 없는 주말, 집에만 있으면 괜히 손해 본 기분이 든다.');
INSERT INTO QUESTION VALUES (9, '취미라도 나중에 써먹을 수 있으면 더 끌린다.');
INSERT INTO QUESTION VALUES (10, '게임이든 뭐든 순위가 나오면 괜히 열심히 하게 된다.');
INSERT INTO QUESTION VALUES (11, '움직일 때 생각이 정리되거나 아이디어가 떠오르는 편이다.');
INSERT INTO QUESTION VALUES (12, '취미는 눈에 보이는 결과가 있어야 실감 난다.');
INSERT INTO QUESTION VALUES (13, '무엇을 하느냐보다, 누구와 하느냐가 더 중요하게 느껴지는 편이다.');
INSERT INTO QUESTION VALUES (14, '취미와 자기 관리의 경계가 꼭 나뉘어야 할 필요는 없다고 생각한다.');
INSERT INTO QUESTION VALUES (15, '알아보고 비교하는 과정 자체가 즐겁다.');

COMMIT;

SELECT * FROM QUESTION;

COMMENT ON COLUMN "QUESTION"."QUESTION_NO" IS '질문 번호 (PK)';

COMMENT ON COLUMN "QUESTION"."QUESTION_CONTENT" IS '질문 내용';

CREATE TABLE "FIND_HOBBY" (
	"QUESTION_NO"	NUMBER		NOT NULL,
	"HOBBY_CODE"	NUMBER		NOT NULL,
	"ANSWER_SCORE"	NUMBER		NOT NULL
);

-- Q1 과정이 예쁘면 만족
INSERT INTO FIND_HOBBY VALUES (1, 2, 3);
INSERT INTO FIND_HOBBY VALUES (1, 5, 1);

-- Q2 쓸모도 있는 게 좋다
INSERT INTO FIND_HOBBY VALUES (2, 3, 3);
INSERT INTO FIND_HOBBY VALUES (2, 1, 1);

-- Q3 관계가 중요
INSERT INTO FIND_HOBBY VALUES (3, 4, 3);
INSERT INTO FIND_HOBBY VALUES (3, 1, 1);

-- Q4 장비·굿즈까지 본다
INSERT INTO FIND_HOBBY VALUES (4, 5, 3);
INSERT INTO FIND_HOBBY VALUES (4, 1, 1);

-- Q5 움직이면 개운
INSERT INTO FIND_HOBBY VALUES (5, 1, 3);
INSERT INTO FIND_HOBBY VALUES (5, 3, 1);

-- Q6 정답 없는 문제 흥미
INSERT INTO FIND_HOBBY VALUES (6, 2, 3);
INSERT INTO FIND_HOBBY VALUES (6, 3, 1);

-- Q7 취향이 분명
INSERT INTO FIND_HOBBY VALUES (7, 2, 2);
INSERT INTO FIND_HOBBY VALUES (7, 5, 1);

-- Q8 주말 집에만 있으면 손해
INSERT INTO FIND_HOBBY VALUES (8, 1, 2);
INSERT INTO FIND_HOBBY VALUES (8, 4, 2);

-- Q9 나중에 써먹을 수 있으면
INSERT INTO FIND_HOBBY VALUES (9, 3, 3);
INSERT INTO FIND_HOBBY VALUES (9, 4, 1);

-- Q10 순위 나오면 열심히
INSERT INTO FIND_HOBBY VALUES (10, 3, 2);
INSERT INTO FIND_HOBBY VALUES (10, 1, 1);

-- Q11 움직이며 아이디어
INSERT INTO FIND_HOBBY VALUES (11, 1, 2);
INSERT INTO FIND_HOBBY VALUES (11, 2, 1);

-- Q12 눈에 보이는 결과
INSERT INTO FIND_HOBBY VALUES (12, 5, 2);
INSERT INTO FIND_HOBBY VALUES (12, 2, 1);

-- Q13 누구와 했는지가 중요
INSERT INTO FIND_HOBBY VALUES (13, 4, 3);

-- Q14 취미 = 자기관리
INSERT INTO FIND_HOBBY VALUES (14, 3, 2);
INSERT INTO FIND_HOBBY VALUES (14, 1, 1);

-- Q15 비교·탐색이 즐겁다
INSERT INTO FIND_HOBBY VALUES (15, 5, 3);
INSERT INTO FIND_HOBBY VALUES (15, 2, 1);

COMMIT;

SELECT * FROM FIND_HOBBY;

COMMENT ON COLUMN "FIND_HOBBY"."QUESTION_NO" IS '질문 번호 (PK)';

COMMENT ON COLUMN "FIND_HOBBY"."HOBBY_CODE" IS '취미 코드 (PK)';

COMMENT ON COLUMN "FIND_HOBBY"."ANSWER_SCORE" IS '답변 점수';

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"COMMENT_NO2"	NUMBER		NOT NULL
);

ALTER TABLE "COMMENT" RENAME COLUMN COMENT_DEL_FL TO COMMENT_DEL_FL;

ALTER TABLE "COMMENT" MODIFY "COMMENT_NO2" NULL;

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호 (PK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMENT_DEL_FL" IS '댓글 삭제 여부';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호 (PK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_NO2" IS '부모 댓글 번호 (FK)';

SELECT * FROM "COMMENT";

CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

-- 댓글 샘플데이터
INSERT INTO "COMMENT"	
VALUES( SEQ_COMMENT_NO.NEXTVAL, '부모 댓글 1',
			  DEFAULT, DEFAULT,	2, 12, NULL);
			 
INSERT INTO "COMMENT"	
VALUES( SEQ_COMMENT_NO.NEXTVAL, '부모 댓글 2',
			  DEFAULT, DEFAULT,	2, 12, NULL);
			 
INSERT INTO "COMMENT"	
VALUES( SEQ_COMMENT_NO.NEXTVAL, '부모 댓글 3',
			  DEFAULT, DEFAULT,	2, 12, NULL);


CREATE TABLE "AUTH_KEY" (
	"AUTH_KEY_CODE"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"AUTH_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"AUTH_KEY"	CHAR(6)		NOT NULL,
	"AUTH_KEY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_CODE" IS '인증키 구분 번호(PK)';

COMMENT ON COLUMN "AUTH_KEY"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_EMAIL" IS '인증 이메일';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY" IS '인증키';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_DATE" IS '인증키 생성일';

CREATE TABLE "COMMENT_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT_LIKE"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "COMMENT_LIKE"."COMMENT_NO" IS '댓글 번호 (PK)';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"BOARD_VIEW_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호 (PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 수정일';

COMMENT ON COLUMN "BOARD"."BOARD_VIEW_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 코드 번호 (PK)';

SELECT * FROM BOARD;

CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '게시글 상세 조회 테스트용 게시글', DEFAULT, NULL, DEFAULT, DEFAULT, 1, 3, NULL, '게시글 상세 조회 테스트용 게시글을 한 번 작성해보았습니다.');

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '공지게시글 상세 조회 테스트용 게시글', DEFAULT, NULL, DEFAULT, DEFAULT, 1, 1, NULL, '공지게시글 상세 조회 테스트용 게시글을 한 번 작성해보았습니다.');

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '취미게시글 상세 조회 테스트용 게시글', DEFAULT, NULL, DEFAULT, DEFAULT, 1, 2, 1, '취미게시글 상세 조회 테스트용 게시글을 한 번 작성해보았습니다.');

COMMIT;

CREATE TABLE "BOARD_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

SELECT * FROM BOARD_LIKE;

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글 번호 (PK)';

CREATE TABLE "PROFILE_IMG" (
	"PROFILE_NO"	NUMBER		NOT NULL,
	"PROFILE_PATH"	VARCHAR2(500)		NOT NULL,
	"PROFILE_ORIGINAL_NAME"	VARCHAR2(300)		NOT NULL,
	"PROFILE_RENAME"	VARCHAR2(100)		NOT NULL,
	"PROFILE_UPDATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_NO" IS '프로필 이미지 번호 (PK)';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_PATH" IS '프로필 이미지 경로';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_ORIGINAL_NAME" IS '프로필 이미지 원본명';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_RENAME" IS '프로필 이미지 변경명';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_UPDATE_DATE" IS '프로필 이미지 업로드일';

COMMENT ON COLUMN "PROFILE_IMG"."MEMBER_NO" IS '회원 번호(PK)';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판 코드 번호 (PK)';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판 명';

SELECT * FROM BOARD_TYPE;	

CREATE TABLE "BOARD_IMG" (
	"BOARD_IMG_NO"	NUMBER		NOT NULL,
	"BOARD_IMG_PATH"	VARCHAR2(500)		NOT NULL,
	"BOARD_IMG_ORIGINAL_NAME"	VARCHAR2(300)		NOT NULL,
	"BOARD_IMG_RENAME"	VARCHAR2(100)		NOT NULL,
	"BOARD_IMG_ORDER"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_NO" IS '게시글 이미지 번호 (PK)';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_PATH" IS '게시글 이미지 경로';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_ORIGINAL_NAME" IS '게시글 이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_RENAME" IS '게시글 이미지 변경명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_ORDER" IS '게시글 이미지 순서';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호 (PK)';

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_REASON"	NVARCHAR2(100)		NOT NULL,
	"REPORT_DETAIL"	VARCHAR2(4000)		NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_STATUS"	VARCHAR2(20)	DEFAULT 'PENDING'	NOT NULL,
	"REPORTER_MEMBER_NO"	NUMBER		NOT NULL,
	"REPORTED_MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고 번호(PK)';

COMMENT ON COLUMN "REPORT"."REPORT_REASON" IS '신고 사유';

COMMENT ON COLUMN "REPORT"."REPORT_DETAIL" IS '신고 상세 내용';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고 날짜';

COMMENT ON COLUMN "REPORT"."REPORT_STATUS" IS '신고 상황';

COMMENT ON COLUMN "REPORT"."REPORTER_MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "REPORT"."REPORTED_MEMBER_NO" IS '회원 번호(PK)';

CREATE TABLE "CS" (
	"CS_NO"	NUMBER		NOT NULL,
	"CS_WRITER_NAME"	NVARCHAR2(10)		NOT NULL,
	"CS_WRITER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"CS_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CS_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"CS_COMPLETE_YN" CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "CS"."CS_NO" IS '문의 번호(PK)';

COMMENT ON COLUMN "CS"."CS_WRITER_NAME" IS '문의 작성자 이름';

COMMENT ON COLUMN "CS"."CS_WRITER_EMAIL" IS '문의 작성자 이메일';

COMMENT ON COLUMN "CS"."CS_WRITE_DATE" IS '문의 작성일';

COMMENT ON COLUMN "CS"."CS_CONTENT" IS '문의 작성 내용';

COMMENT ON COLUMN "CS"."CS_COMPLETE_YN" IS '문의 확인 여부';

ALTER TABLE "CS" ADD CONSTRAINT "PK_CS" PRIMARY KEY (
	"CS_NO"
);

CREATE SEQUENCE SEQ_CS_NO NOCACHE;

SELECT r.REPORT_NO, reporter.MEMBER_NICKNAME REPORTER_NICKNAME, reported.MEMBER_NICKNAME REPORTED_NICKNAME, 
r.REPORT_REASON, TO_CHAR(REPORT_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') REPORT_DATE
FROM REPORT r
JOIN MEMBER reporter ON (r.REPORTER_MEMBER_NO = reporter.MEMBER_NO)
JOIN MEMBER reported ON (r.REPORTED_MEMBER_NO = reported.MEMBER_NO)
WHERE r.REPORT_STATUS = 'PENDING';

CREATE SEQUENCE SEQ_REPORT_NO NOCACHE;

ALTER TABLE REPORT MODIFY REPORT_DETAIL NULL;

SELECT * FROM REPORT;

ALTER TABLE "HOBBY" ADD CONSTRAINT "PK_HOBBY" PRIMARY KEY (
	"HOBBY_CODE"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "PENALTY" ADD CONSTRAINT "PK_PENALTY" PRIMARY KEY (
	"PENALTY_NO"
);

ALTER TABLE "MEMBER_HOBBY" ADD CONSTRAINT "PK_MEMBER_HOBBY" PRIMARY KEY (
	"MEMBER_NO",
	"HOBBY_CODE"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY (
	"QUESTION_NO"
);

ALTER TABLE "FIND_HOBBY" ADD CONSTRAINT "PK_FIND_HOBBY" PRIMARY KEY (
	"QUESTION_NO",
	"HOBBY_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"AUTH_KEY_CODE"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "PK_COMMENT_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"COMMENT_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"BOARD_NO"
);

ALTER TABLE "PROFILE_IMG" ADD CONSTRAINT "PK_PROFILE_IMG" PRIMARY KEY (
	"PROFILE_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"BOARD_IMG_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "HOBBY" ADD CONSTRAINT "FK_HOBBY_TO_HOBBY_1" FOREIGN KEY (
	"PARENT_CODE"
)
REFERENCES "HOBBY" (
	"HOBBY_CODE"
);

ALTER TABLE "HOBBY" ADD CONSTRAINT "FK_BOARD_TYPE_TO_HOBBY_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "PENALTY" ADD CONSTRAINT "FK_MEMBER_TO_PENALTY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_HOBBY" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_HOBBY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_HOBBY" ADD CONSTRAINT "FK_HOBBY_TO_MEMBER_HOBBY_1" FOREIGN KEY (
	"HOBBY_CODE"
)
REFERENCES "HOBBY" (
	"HOBBY_CODE"
);

ALTER TABLE "FIND_HOBBY" ADD CONSTRAINT "FK_QUESTION_TO_FIND_HOBBY_1" FOREIGN KEY (
	"QUESTION_NO"
)
REFERENCES "QUESTION" (
	"QUESTION_NO"
);

ALTER TABLE "FIND_HOBBY" ADD CONSTRAINT "FK_HOBBY_TO_FIND_HOBBY_1" FOREIGN KEY (
	"HOBBY_CODE"
)
REFERENCES "HOBBY" (
	"HOBBY_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"COMMENT_NO2"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "FK_MEMBER_TO_AUTH_KEY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "PROFILE_IMG" ADD CONSTRAINT "FK_MEMBER_TO_PROFILE_IMG_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"REPORTER_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_2" FOREIGN KEY (
	"REPORTED_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

COMMIT;

SELECT * FROM AUTH_KEY;
SELECT * FROM BOARD;
SELECT * FROM BOARD_LIKE;
SELECT * FROM BOARD_TYPE;
SELECT * FROM BOARD_CATEGORY;
SELECT * FROM "COMMENT";
SELECT * FROM COMMENT_LIKE;
SELECT * FROM FIND_HOBBY;
SELECT * FROM HOBBY;
SELECT * FROM MEMBER;
SELECT * FROM MEMBER_HOBBY;
SELECT * FROM QUESTION;
SELECT * FROM BOARD_IMG;
SELECT * FROM REPORT;
SELECT * FROM PROFILE_IMG;
SELECT * FROM PENALTY;
SELECT * FROM CS;

UPDATE "MEMBER" SET AUTHOR_LEVEL = 2
WHERE MEMBER_NO = 1;

DELETE FROM MEMBER;

COMMIT;



SELECT HOBBY_CODE  FROM "MEMBER"
JOIN "MEMBER_HOBBY" USING (MEMBER_NO)
WHERE MEMBER_NO = 19;

	SELECT LISTAGG(REPORT_REASON, ', ')
			WITHIN GROUP (ORDER BY REPORT_REASON) AS PENALTY_REASON
		FROM (
			SELECT REPORT_REASON,
				DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
			FROM REPORT
			WHERE REPORTED_MEMBER_NO = 1
			GROUP BY REPORT_REASON
		)
		WHERE RNK = 1;
	
SELECT *
		FROM (
			SELECT
			PENALTY_NO,
			PENALTY_TYPE,
			PENALTY_START_DATE,
			PENALTY_END_DATE,
			PENALTY_REASON,
			PENALTY_STATUS,
			MEMBER_NO,
			MEMBER_NICKNAME
			FROM PENALTY
			JOIN MEMBER USING (MEMBER_NO)
			WHERE PENALTY_STATUS = 'ACTIVE'
			ORDER BY
				CASE
					WHEN PENALTY_TYPE = 'PERMANENT' THEN 1
					WHEN PENALTY_TYPE = 'SUSPEND' THEN 2
				END,
			PENALTY_NO DESC);


SELECT COUNT(*)
		FROM REPORT
		WHERE REPORTER_MEMBER_NO = 1
		AND TO_CHAR(REPORT_DATE, 'YYYY-MM-DD') = '2026-01-07';